[tool.poetry]
name = "django_template_component"
version = "0.1.0"
description = ""
authors = ["Neil Lyons <nwjlyons@googlemail.com>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
Django = "^4.0.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
